name: Scraper Workflow

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 使用的 Node.js 版本

      - name: Install dependencies
        run: |
          cd scraper
          npm install puppeteer
          ls -al scraper  # 列出内容以确认文件存在

      - name: Run scraper
        run: |
          cd scraper
          node scrape.js || echo 'Scraping failed'  # 捕获脚本失败信息并输出

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "your-email@example.com"  # 替换为你的 email

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./scraper  # 修改为实际输出目录
